### ISSUE TITLE
Problem with `isErr` and `isOK`

### ISSUE THREAD

**Issue by patroza** [gDelgado14/neverthrow#1]
Hi,

very nice stuff!

the typings of isErr and isOk should probably be updated:
```
    isOk(): this is Ok<T, E>;
    isErr(): this is Err<T, E>;
```

a true isOk should always return is Ok
a true isErr should always return is Err

Right now however you hardcoded on Ok both isOk and isErr to is Ok.
and on Err both isOk and isErr to is Err.

This breaks the auto type inference in typescript. ie if I check for result.isErr(), then it actually thinks result is Ok, not Err.

ie https://github.com/patroza/neverthrow/commit/59813c2b89f726fee0c71ba7cc13dbe0a78d538c

**Comment by gDelgado14** [comment]
Fixed, this has been shipped in version 1.0.4 (available now on npm). See this commit for the fix:

https://github.com/gDelgado14/neverthrow/commit/fe4df506507655830fcb3063052aa353a5d1b00e
