### ISSUE TITLE
Documentation mismatch for match() 

### ISSUE THREAD

**Issue by TheFalseFriend** [gDelgado14/neverthrow#11]
Been tinkering with neverthrow - it's a nice wee library @gDelgado14.

I've come across an inconsistency between the documentation (including at [npm](https://www.npmjs.com/package/neverthrow)).

The docs state for match() the following;
```
match<U, A>(
  okFn: (t:  T) =>  U,
  errFn: (e:  E) =>  A
):  U | A => { ... }
```
This suggests we could get back an `A` or a `U` when we call match(). However the code as _currently implemented_ is written as;
```
match<U, A>(
  okFn: (t:  T) =>  A,
  errFn: (e:  E) =>  A
):  A => { ... }
```  
Therefore in actual usage we can only get back an `A`. 

My questions are thus:
* which case is correct? Presumably the ```U | A``` case.
* _if_ the ```A``` case is correct, I'd be curious to understand the specific reason for enforcing more restrictive usage, from a types perspective (I'm new to TypeScript)?
* why implement match() as a property and not a method?

Thanks in advance!

**Comment by gDelgado14** [comment]
Good catch @TheFalseFriend! 

> which case is correct? Presumably the U | A case.

The documented type definition was accurate at one point. See this repo's initial commit: 

[Here](https://github.com/gDelgado14/neverthrow/commit/3518425c3884e93b5915cf0205ce58355fd0c766#diff-13618125a1b532b291c07ad8ac3dc6b8R51) and [here](https://github.com/gDelgado14/neverthrow/commit/3518425c3884e93b5915cf0205ce58355fd0c766#diff-13618125a1b532b291c07ad8ac3dc6b8R95)

I can't recall why I changed it, but I did so here:

https://github.com/gDelgado14/neverthrow/commit/a07287e49cbe6b9276466966f418743051e0192c

However, I forgot to update the docs 🙈

I am always happy to accept pull requests to fix things such as incorrect documentation!

**Comment by gDelgado14** [comment]
> if the A case is correct, I'd be curious to understand the specific reason for enforcing more restrictive usage, from a types perspective (I'm new to TypeScript)?

Returning `U | A` leads to cumbersome code, especially when your `U` and your `A` don't have a related field in order for the TypeScript compiler to discern if your value is indeed an `A` or a `U`. 

For more info on what I mean, check out the TS docs on [discriminated unions](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions).

Note that your `A` can be a generic, such as an `Either`. So your `A` Could be `Either<MyErrorType, MySuccessType>`

**Comment by gDelgado14** [comment]
> why implement match() as a property and not a method?

No real good reason. I think at the time, I was getting some annoying compiler errors.

**Comment by gDelgado14** [comment]
Closing this issue since it was fixed in https://github.com/gDelgado14/neverthrow/pull/12
