### ISSUE TITLE
Add `asyncMatch` and `asyncAndThen`

### ISSUE THREAD

**Issue by patroza** [gDelgado14/neverthrow#2]
ie:
- https://github.com/patroza/neverthrow/commit/cf0506db790e26fe75466273e9c16674990a7e39
- https://github.com/patroza/neverthrow/commit/1d3ecfb531e805b068f7785f94b4744f3ef9e83b

This opens up some additional concerns, as to continue from `asyncAndThen`, we can no longer chain it, and instead we have to branch inside it to chain it, either with (await ..) or by using `.then()` this breaks some of the elegancy of the piping.

Some thoughts I have on the subject:
- Explore generators (`yield`), this may be something we could use as an equivelent to Computation Expressions in F# (sample of a custom ResultBuilder is available in F# for fun and profit)
- Explore extending `Promise`
- Explore an approach that would inverse `Promise<` and `Result<` so `Result<Promise<` instead of `Promise<Result<`

While playing with the tech, I get a familiar feeling to when working with rxjs..

**Comment by gDelgado14** [comment]
Hey Pat,

Just wanted to post a msg here to let u know that I've read both your issues and I'm just thinking about them. Don't want to make it seem like I'm ignoring your issues!

**Comment by gDelgado14** [comment]
Hey @patroza, sorry for the super late reply. I've been noodling on this and came up with an API that I've been using in my personal projects. Curious to know what you think. 

Right now there's a `chain` method that combines two async `Result`s and a `chain3` that combines three async `Result`s. 

```typescript
export const chain = async <T1, T2, E>(
  r1: Promise<Result<T1, E>>,
  r2: (v: T1) => Promise<Result<T2, E>>
): Promise<Result<T2, E>> => {
  const inner = await r1

  const mapped = await inner.asyncMap(r2)

  return mapped.andThen((inner) => inner)
}


export const chain3 = async <T1, T2, T3, E>(
  r1: Promise<Result<T1, E>>,
  r2: (v: T1) => Promise<Result<T2, E>>,
  r3: (v: T2) => Promise<Result<T3, E>>
): Promise<Result<T3, E>> => {
  const chained = await chain(r1, r2)

  const mapped = await chained.asyncMap(r3)

  return mapped.andThen((inner) => inner)
}
```


Here's an example of how I'm using it in my back end personal project.

<img width="763" alt="Screen Shot 2019-11-08 at 10 16 05 AM" src="https://user-images.githubusercontent.com/10621548/68487307-d38a2600-0210-11ea-8bea-a9905b3a6d7f.png">

**Comment by AlexLeung** [comment]
I ended up just switching to `fp-ts` and using `TaskEither`

**Comment by gDelgado14** [comment]
This has been addressed in the new release:

https://github.com/gDelgado14/neverthrow/releases/tag/v2.2.0

There's a new api available that implements my above suggestion.
