### ISSUE TITLE
Make `value` and `error` `public readonly`

### ISSUE THREAD

**Issue by patroza** [gDelgado14/neverthrow#3]
`constructor(public readonly value: T)`

`constructor(public readonly error: E)`

So when the type is narrowed, you can just access it:
`if (x.isErr()) { console.error(x.error) }`
`if (x.isOk()) { console.log(x.value) }`

**Comment by gDelgado14** [comment]
Why not just use `_unsafeUnwrap` and `_unsafeUnwrapErr`?

**Comment by patroza** [comment]
Because:
- it’s long
- they’re methods
- it speaks not the truth: when you check isErr/isOk and narrow the type it is no longer unsafe to unwrap
- checking and then accessing .error and .value is more like the imperative equivalent to .match

**Comment by gDelgado14** [comment]
I'll publish soon. Having issues publishing to npm right now.

**Comment by gDelgado14** [comment]
Published!
