### ISSUE TITLE
Type 'Promise<Err<unknown, NotFoundException> | Ok<{}, unknown>>' is not assignable to type 'Promise<Result<any, HttpException>>'.

### ISSUE THREAD

**Issue by izio38** [gDelgado14/neverthrow#6]
Hi.

First, I want to say thank you. It's an awesome package with a lot of possibility. I love Rust, and I think this type could avoid a big mess.

However, I'm encountering an issue while implementing a custom HttpException Error.

This is my HttpException class:
```ts
export class HttpException extends Error {
  errorMetadata: any;

  constructor(message: string = "Not Found.", errorMetadata?: any) {
    super(message);
    Error.captureStackTrace(this);

    this.errorMetadata = errorMetadata;
  }
}
``` 

I want my Axios service to return an error of this type brought to the `Err` type.:
```ts
private handleError(error: any) {
    return err(new NotFoundException());
    // I've also tried with new Error(), it doesn't work too.
}

public get(url: string, options?: AxiosRequestConfig): Promise<Result<any, HttpException>> {
    return axios
      .get(url, options)
      .then(response => {
        const data = R.pathOr({}, ["data"], response);
        return ok(data);
      })
      .catch(this.handleError);
}
``` 

Full TypeScript compilation error:
```
Type 'Promise<Err<unknown, NotFoundException> | Ok<{}, unknown>>' is not assignable to type 'Promise<Result<any, HttpException>>'.
  Type 'Err<unknown, NotFoundException> | Ok<{}, unknown>' is not assignable to type 'Result<any, HttpException>'.
    Type 'Ok<{}, unknown>' is not assignable to type 'Result<any, HttpException>'.
      Type 'Ok<{}, unknown>' is not assignable to type 'Ok<any, HttpException>'.
        Type '{}' is missing the following properties from type 'HttpException': errorMetadata, name, messagets(2322)
```

What am I doing wrong?
I tested some other possibilities, it doesn't seems to work with complex types.

**Comment by davidgiggs** [comment]
Is this because handleError isn't within the scope of the get method and therefore can't infer the result type (Result<any, HttpException>)?

I had a similar issue when returning "err" from an observable flatMap. 

Try casting either the HandlerError method like this:-
private handleError(error: any): Result<any, HttpException> {
    return err(new NotFoundException());
    // I've also tried with new Error(), it doesn't work too.
}
Or by casting the actual method call:-
this.HandleError() as Result<any, HttpException>.

I'm also guessing you could do what Giorgio does in his parlez-vous/server examples and use a type alias, e.g. :-
type myHttpException = Result<any, HttpException> and set that as the HandleError return type.

**Comment by gDelgado14** [comment]
@izio38 My apologies for the late response. I always read these compiler error traces from bottom up. And it looks like the type annotation in your `get` method is stating that the `Ok` and `Err` variants must be `Ok(any)` and `Err(HttpException)`. However, I do not think the compiler has sufficient information to infer that your call to `.catch(this.handleError)` and `return ok(data);` are indeed abiding by the type annotation. What I'd recommend is to explicitly annotate or cast your invocations to provide more info to the compiler.
